#!/bin/sh

# Set DEFAULT_PROJECT to path of default Laravel
# home folder, don't forget trailing slash
DEFAULT_PROJECT="/path/to/default/laravel/project/"

# build list of directories to check
PATHS=''
BUILD='/'
for P in `pwd | tr "/" " "`; do
	BUILD="$BUILD$P/"
	PATHS="$BUILD $PATHS"
done;

# Execute first found artisan from path upward
for P in $PATHS; do
	CMD="${P}artisan"
	if [ -e $CMD ]; then
		php $CMD $@
		exit
	fi
done;

echo "* DEFAULT PROJECT *"
php "${DEFAULT_PROJECT}artisan" $@
